# Modify the official OmniLearned to match our network size convention
net:
 base_dim: 128
 num_transformers: 4  # modified from default '8'
 num_transformers_head: 2
 num_tokens: 1  # modified from default '4'
 num_heads: 8
 mlp_ratio: 4  # modified from default '2'

 checkpoint_blocks: false  # new option

defaults:
 - tag_PET2-S
