lr: ${eval:'${training.lr_base} * 2 ** (-${model.net.size}) * ${model.net.helpers.lr_factor}'}
lr_base: 2.5e-4
batchsize: 512
iterations: 1000000
scheduler: CosineAnnealingLR
optimizer: AdamW

validate_every_n_steps: 100000

defaults:
 - tag_default
