_target_: experiments.tagging.wrappers.SaltWrapper
in_channels: null
out_channels: null
use_amp: false
add_fourmomenta_backbone: false

net:
  _target_: salt.models.SaltModel
  
  init_nets:
    - input_name: tracks
      global_object: jets
      variables: { jets: [], tracks: []  }
      dense_config:
        output_size: &embed_dim 32
        hidden_layers: [64]
        activation: &activation ReLU

  encoder:
    _target_: salt.models.TransformerEncoder
    embed_dim: *embed_dim
    num_layers: 2
    out_dim: &out_dim 32
    mha_config:
      num_heads: 4
      attention: { class_path: salt.models.ScaledDotProductAttention }
    dense_config:
      activation: *activation

  pool_net:
    _target_: salt.models.GlobalAttentionPooling
    input_size: *out_dim

  tasks:
    _target_: torch.nn.ModuleList
    modules:
      - _target_: salt.models.ClassificationTask
        name: jets_classification
        input_name: jets
        label: top_label
        class_names: [qcd, top]
        use_class_dict: True
        loss:
          _target_: torch.nn.CrossEntropyLoss
        dense_config: &task_dense_config
          input_size: *out_dim
          output_size: 2
          hidden_layers: [128, 64, 32]
          activation: *activation

defaults:
  - framesnet: identity
