_target_: experiments.tagging.wrappers.SaltWrapper
in_channels: &in_channels null
out_channels: null
use_amp: false
attention_backend: default_attention
add_fourmomenta_backbone: false
mean_aggregation: true

init_dense:
  _target_: salt.models.Dense
  input_size: null
  output_size: &embed_dim 32
  hidden_layers: [128]
  activation: &activation ReLU

net:
  _target_: salt.models.transformer_v2.TransformerV2
  embed_dim: *embed_dim
  num_layers: 2
  out_dim: &out_dim 32
  drop_registers: true
  do_final_norm: false
  attn_type: torch-math
  attn_kwargs:
    num_heads: 2
    attn_type: torch-math
  dense_kwargs:
    hidden_dim: 128
    activation: *activation

task_dense:
  _target_: salt.models.Dense
  input_size: *out_dim
  output_size: 1
  hidden_layers: [128, 64, 32]
  activation: *activation

pool_net:
  _target_: salt.models.GlobalAttentionPooling
  input_size: *out_dim

  # tasks:
  #   _target_: torch.nn.ModuleList
  #   modules:
  #     - _target_: salt.models.ClassificationTask
  #       name: jets_classification
  #       input_name: jets
  #       label: top_label
  #       class_names: [qcd, top]
  #       use_class_dict: True
  #       loss:
  #         _target_: torch.nn.CrossEntropyLoss
  #       dense_config: &task_dense_config
  #         input_size: *out_dim
  #         output_size: 2
  #         hidden_layers: [128, 64, 32]
  #         activation: *activation

defaults:
  - framesnet: identity
