exp_type: pretrain
exp_name: pretrain_local

data:
 canonicalize: beam_y
 data_dir: data
 dataset_name: pretrain
 num_workers: 4
 prefetch_factor: null
 train_frac: 1.0
 val_frac: 0.1
 test_frac: 0.1

evaluation:
 eval_set: [test]

defaults:
 - training: jc_transformer
 - tagging
 - _self_
