exp_type: top_omni
exp_name: top_omni_local

data:
 data_dir: data
 num_workers: 4
 prefetch_factor: null
 use_scalars: false

defaults:
 - training: top_transformer
 - tagging
 - override /model: tag_top_transformer
 - _self_
